name: Reusable workflows CI .NET

on:
  workflow_call:
    inputs:
      dotnetversion:
        description: 'Version to build'
        required: false
        default: '8.0.x'
        type: string
      artifactname:
        description: 'Artifact name'
        required: false
        default: 'app-package'
        type: string
      buildconfiguration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'produccion'
        type: string
    secrets:
      SERVICE_PRINCIPAL:
        description: 'Azure Service Principal'
        required: true
      OIDC_AWS_ARN:
        description: 'AWS OIDC Role ARN'
        required: true       

env:
  LAMBDA_HEADER: 'sesion5_github_2026::sesion5_github_2026_Function::FunctionHandler'
  LAMBDA_RUNTIME: 'dotnet8'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      app_version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version from changelog
        id: extract_version
        run: |
          VERSION=$(grep -oPm1 "(?<=## \[)[^]]+" CHANGELOG.md)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            
  build:
    runs-on: windows-latest
    needs: extract-version
    steps:
      - name: Muestra version
        run: echo "version en ${{ needs.extract_version.outputs.app_version }}"
      
      - name: Build and test
        uses: AngelEvaristo/sesion5_github_2026_template/.github/actions/build-test@main
        with:
          dotnetversion: ${{ inputs.dotnetversion }}
          buildconfiguration: ${{ inputs.buildconfiguration }}
          run-tests: true

    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Install dotnet
    #     uses: actions/setup-dotnet@v5
    #     with:
    #       dotnet-version: ${{ inputs.dotnetversion }}

    #   - name: Restore
    #     run: dotnet restore

    #   - name: build
    #     run: dotnet build --no-restore --configuration ${{ inputs.buildconfiguration }}
      
      - name: publish
        run: dotnet publish --no-restore --configuration ${{ inputs.buildconfiguration }} --output ./publish
    
      - name: zip artifact
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ${{ inputs.artifactname }}.zip
        shell: pwsh  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactname }}
          path: ${{ inputs.artifactname }}.zip 

  test-job-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run docker action
        uses: docker://alpine:latest
        with:   
          args: echo "Running tests in a Docker container"

  deploy-azure:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifactname }}  

      - name: Mostrar variable
        run: echo "version en ${{ vars.VARIABLE_GITHUB }} | artifact name ${{ inputs.artifactname }} | webapp name ${{ vars.WEBAPP_NAME }} | environment ${{ inputs.environment }}"

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL }}  

      - name: deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.WEBAPP_NAME }}
          package: ${{ inputs.artifactname }}.zip

  deploy-aws:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifactname }}  

      - name: Mostrar variable
        run: echo "version en ${{ vars.VARIABLE_GITHUB }} | artifact name ${{ inputs.artifactname }} | lambda name ${{ vars.LAMBDA_NAME }} | environment ${{ inputs.environment }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_AWS_ARN }}
          aws-region: us-east-1
          
      - name: deploy lambda
        run: |
          aws lambda update-function-configuration --function-name ${{ vars.LAMBDA_NAME }} --handler ${{ env.LAMBDA_HEADER }} --runtime ${{ env.LAMBDA_RUNTIME }}
          aws lambda wait function-updated --function-name ${{ vars.LAMBDA_NAME }}
          aws lambda update-function-code --function-name ${{ vars.LAMBDA_NAME }} --zip-file fileb://${{ inputs.artifactname }}.zip --publish            
          aws lambda wait function-updated --function-name ${{ vars.LAMBDA_NAME }}   

