name: Reusable workflows CI .NET

on:
  workflow_call:
    inputs:
      dotnetversion:
        description: 'Version to build'
        required: false
        default: '8.0.x'
        type: string
      artifactname:
        description: 'Artifact name'
        required: false
        default: 'app-package'
        type: string
      buildconfiguration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version from changelog
        id: extract_version
        run: |
          VERSION=$(grep -oPm1 "(?<=## \[)[^]]+" CHANGELOG.md)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            
  build:
    runs-on: windows-latest
    needs: extract-version
    steps:
      - name: Muestra version
        run: echo "version en ${{ needs.extract_version.outputs.app_version }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnetversion }}

      - name: Restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore --configuration ${{ inputs.buildconfiguration }}
      
      - name: publish
        run: dotnet publish --no-restore --configuration ${{ inputs.buildconfiguration }} --output ./publish
    
      - name: zip artifact
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ${{ inputs.artifactname }}.zip
        shell: pwsh  

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactname }}     